### ISSUE TITLE
Adding an empty __init__.py

### ISSUE THREAD

**Issue by ppetr** [dougz/trueskill#2]
Would you mind adding an empty file `__init__.py` so that I can use your project directly as a submodule in my [tremstat](https://github.com/ppetr/tremstats) project?
And perhaps also adding `.gitignore` to ignore *.pyc files. Thanks a lot.

**Comment by ppetr** [comment]
I didn't realize that the projects has several forks that already have that (I'm new to github).

**Comment by dougz** [comment]
good idea; done.

On Sun, Apr 22, 2012 at 5:18 AM, Petr Pudlak <
reply@reply.github.com

> wrote:
> 
> Would you mind adding an empty file `__init__.py` so that I can use your
> project directly as a submodule in my [tremstat](https://github.com/ppetr/tremstats) project?
> And perhaps also adding `.gitignore` to ignore *.pyc files. Thanks a lot.
